# Generated by Django 5.0.2 on 2024-04-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_bus_id_bus_bus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='time',
        ),
    ]
