# Generated by Django 5.0.2 on 2024-04-05 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_bus_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
