# Generated by Django 5.0.2 on 2024-05-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_remove_bus_unique_migration_host_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='rem',
            field=models.IntegerField(default=models.IntegerField(default=30)),
        ),
    ]
