# Generated by Django 5.0.2 on 2024-05-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_bus_rem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='rem',
            field=models.IntegerField(),
        ),
    ]
