# Generated by Django 5.0.2 on 2024-07-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_bus_rem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='dest',
        ),
        migrations.RemoveField(
            model_name='book',
            name='busid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.AddField(
            model_name='book',
            name='src',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
