# Generated by Django 5.0.2 on 2026-05-08 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(default=0)),
                ('schedule_id', models.IntegerField(default=0)),
                ('nos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'List of Books',
            },
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=30)),
                ('capacity', models.IntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'List of Busses',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phno', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule1',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=30)),
                ('dest', models.CharField(max_length=30)),
                ('rem', models.IntegerField()),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('status', models.CharField(default='AVAILABLE', max_length=20)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.buses')),
            ],
            options={
                'verbose_name_plural': 'List of Schedules',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_no', models.CharField(max_length=5)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.book')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.schedule1')),
            ],
            options={
                'verbose_name_plural': 'List of Seats',
            },
        ),
        migrations.AddConstraint(
            model_name='schedule1',
            constraint=models.UniqueConstraint(fields=('bus_id', 'date', 'departure_time'), name='unique_schedule_combination'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('schedule_id', 'seat_no'), name='unique_seat_combination'),
        ),
    ]
