# Generated by Django 5.0.2 on 2024-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_bus_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bus',
            name='rem',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
