# Generated by Django 5.0.2 on 2024-04-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_remove_book_dest_remove_book_source'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.UniqueConstraint(fields=('bus_name', 'date', 'time'), name='unique_migration_host_combination'),
        ),
    ]
